# Generated by Django 4.2.6 on 2023-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sumApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name = "chatdata",
            name = "isQuestion",
            field = models.BooleanField(default = False),
        ),
    ]
