# Generated by Django 4.2.6 on 2023-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sumApp", "0002_chatdata_isquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name = "chatdata",
            name = "isAI",
            field = models.BooleanField(default = False),
        ),
    ]
