# Generated by Django 4.2.6 on 2023-11-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sumApp", "0004_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(default="DEFAULT", max_length=255),
        ),
    ]
